/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 8030f467687814b92b9f0b4cf022b127)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "HackathonMentor";
	}
	interface Env {
		AI: Ai;
		HackathonMentor: DurableObjectNamespace<import("./src/server").HackathonMentor>;
	}
}
interface Env extends Cloudflare.Env {}
