/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 335c15ad9cb5f0d200544d0a77c24c85)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "HackathonMentor";
	}
	interface Env {
		AI: Ai;
		ASSETS: Fetcher;
		HackathonMentor: DurableObjectNamespace<import("./src/server").HackathonMentor>;
	}
}
interface Env extends Cloudflare.Env {}
